//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 04:55:52 PM CET 
//

@XmlSchema(namespace  = "omi.xsd", 
xmlns = {
		@XmlNs(prefix="omi", namespaceURI = "omi.xsd")},
		elementFormDefault = QUALIFIED)
package de.biba.omi;

import static javax.xml.bind.annotation.XmlNsForm.QUALIFIED;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;