//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.01 at 03:51:54 PM CET 
//

@XmlSchema(namespace = "odf.xsd", elementFormDefault = QUALIFIED, 
xmlns = @XmlNs(
        prefix="odf", 
        namespaceURI = "odf.xsd"))
package de.biba.odf;

import static javax.xml.bind.annotation.XmlNsForm.QUALIFIED;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;