//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.23 at 12:09:57 PM CET 
//


package de.biba.mediator.converter.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DualExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DualExpression">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Left" type="{}SingleExpression"/>
 *         &lt;element name="Right" type="{}SingleExpression"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DualExpression", propOrder = {
    "left",
    "right"
})
public class DualExpression {

    @XmlElement(name = "Left", required = true)
    protected SingleExpression left;
    @XmlElement(name = "Right", required = true)
    protected SingleExpression right;

    /**
     * Gets the value of the left property.
     * 
     * @return
     *     possible object is
     *     {@link SingleExpression }
     *     
     */
    public SingleExpression getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleExpression }
     *     
     */
    public void setLeft(SingleExpression value) {
        this.left = value;
    }

    /**
     * Gets the value of the right property.
     * 
     * @return
     *     possible object is
     *     {@link SingleExpression }
     *     
     */
    public SingleExpression getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleExpression }
     *     
     */
    public void setRight(SingleExpression value) {
        this.right = value;
    }

}
