//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.23 at 12:09:57 PM CET 
//


package de.biba.mediator.converter.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SingleExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleExpression">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Add" type="{}DualExpression"/>
 *           &lt;element name="Sub" type="{}DualExpression"/>
 *           &lt;element name="Multiply" type="{}DualExpression"/>
 *           &lt;element name="Divide" type="{}DualExpression"/>
 *           &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *           &lt;element name="Input" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Pow" type="{}SingleExpression"/>
 *           &lt;element name="Sqrt" type="{}SingleExpression"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleExpression", propOrder = {
    "add",
    "sub",
    "multiply",
    "divide",
    "value",
    "input",
    "pow",
    "sqrt"
})
public class SingleExpression {

    @XmlElement(name = "Add")
    protected DualExpression add;
    @XmlElement(name = "Sub")
    protected DualExpression sub;
    @XmlElement(name = "Multiply")
    protected DualExpression multiply;
    @XmlElement(name = "Divide")
    protected DualExpression divide;
    @XmlElement(name = "Value")
    protected Double value;
    @XmlElement(name = "Input")
    protected String input;
    @XmlElement(name = "Pow")
    protected SingleExpression pow;
    @XmlElement(name = "Sqrt")
    protected SingleExpression sqrt;

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link DualExpression }
     *     
     */
    public DualExpression getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link DualExpression }
     *     
     */
    public void setAdd(DualExpression value) {
        this.add = value;
    }

    /**
     * Gets the value of the sub property.
     * 
     * @return
     *     possible object is
     *     {@link DualExpression }
     *     
     */
    public DualExpression getSub() {
        return sub;
    }

    /**
     * Sets the value of the sub property.
     * 
     * @param value
     *     allowed object is
     *     {@link DualExpression }
     *     
     */
    public void setSub(DualExpression value) {
        this.sub = value;
    }

    /**
     * Gets the value of the multiply property.
     * 
     * @return
     *     possible object is
     *     {@link DualExpression }
     *     
     */
    public DualExpression getMultiply() {
        return multiply;
    }

    /**
     * Sets the value of the multiply property.
     * 
     * @param value
     *     allowed object is
     *     {@link DualExpression }
     *     
     */
    public void setMultiply(DualExpression value) {
        this.multiply = value;
    }

    /**
     * Gets the value of the divide property.
     * 
     * @return
     *     possible object is
     *     {@link DualExpression }
     *     
     */
    public DualExpression getDivide() {
        return divide;
    }

    /**
     * Sets the value of the divide property.
     * 
     * @param value
     *     allowed object is
     *     {@link DualExpression }
     *     
     */
    public void setDivide(DualExpression value) {
        this.divide = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInput(String value) {
        this.input = value;
    }

    /**
     * Gets the value of the pow property.
     * 
     * @return
     *     possible object is
     *     {@link SingleExpression }
     *     
     */
    public SingleExpression getPow() {
        return pow;
    }

    /**
     * Sets the value of the pow property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleExpression }
     *     
     */
    public void setPow(SingleExpression value) {
        this.pow = value;
    }

    /**
     * Gets the value of the sqrt property.
     * 
     * @return
     *     possible object is
     *     {@link SingleExpression }
     *     
     */
    public SingleExpression getSqrt() {
        return sqrt;
    }

    /**
     * Sets the value of the sqrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleExpression }
     *     
     */
    public void setSqrt(SingleExpression value) {
        this.sqrt = value;
    }

}
