//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 10:54:42 PM CET 
//


package de.biba.wrapper.newSQLWrapper.Mapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinedTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JoinedTable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FirstTable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecondTable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JoinCondition" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="joinType" use="required" type="{}JoinType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JoinedTable", propOrder = {
    "firstTable",
    "secondTable",
    "joinCondition"
})
@XmlSeeAlso({
    MultiJoinedTable.class
})
public class JoinedTable {

    @XmlElement(name = "FirstTable", required = true)
    protected String firstTable;
    @XmlElement(name = "SecondTable", required = true)
    protected String secondTable;
    @XmlElement(name = "JoinCondition", required = true)
    protected List<String> joinCondition;
    @XmlAttribute(name = "joinType", required = true)
    protected JoinType joinType;

    /**
     * Gets the value of the firstTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstTable() {
        return firstTable;
    }

    /**
     * Sets the value of the firstTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstTable(String value) {
        this.firstTable = value;
    }

    /**
     * Gets the value of the secondTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondTable() {
        return secondTable;
    }

    /**
     * Sets the value of the secondTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondTable(String value) {
        this.secondTable = value;
    }

    /**
     * Gets the value of the joinCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the joinCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJoinCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getJoinCondition() {
        if (joinCondition == null) {
            joinCondition = new ArrayList<String>();
        }
        return this.joinCondition;
    }

    /**
     * Gets the value of the joinType property.
     * 
     * @return
     *     possible object is
     *     {@link JoinType }
     *     
     */
    public JoinType getJoinType() {
        return joinType;
    }

    /**
     * Sets the value of the joinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JoinType }
     *     
     */
    public void setJoinType(JoinType value) {
        this.joinType = value;
    }

}
