//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 10:54:42 PM CET 
//


package de.biba.wrapper.newSQLWrapper.Mapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClassMapping" type="{}ClassMapping" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ObjectPropertyMapping" type="{}ObjectPropertyMapping" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DatatypePropertyMapping" type="{}DatatypePropertyMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classMapping",
    "objectPropertyMapping",
    "datatypePropertyMapping"
})
@XmlRootElement(name = "Mapping")
public class Mapping {

    @XmlElement(name = "ClassMapping")
    protected List<ClassMapping> classMapping;
    @XmlElement(name = "ObjectPropertyMapping")
    protected List<ObjectPropertyMapping> objectPropertyMapping;
    @XmlElement(name = "DatatypePropertyMapping")
    protected List<DatatypePropertyMapping> datatypePropertyMapping;

    /**
     * Gets the value of the classMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassMapping }
     * 
     * 
     */
    public List<ClassMapping> getClassMapping() {
        if (classMapping == null) {
            classMapping = new ArrayList<ClassMapping>();
        }
        return this.classMapping;
    }

    /**
     * Gets the value of the objectPropertyMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectPropertyMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectPropertyMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectPropertyMapping }
     * 
     * 
     */
    public List<ObjectPropertyMapping> getObjectPropertyMapping() {
        if (objectPropertyMapping == null) {
            objectPropertyMapping = new ArrayList<ObjectPropertyMapping>();
        }
        return this.objectPropertyMapping;
    }

    /**
     * Gets the value of the datatypePropertyMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datatypePropertyMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatatypePropertyMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatatypePropertyMapping }
     * 
     * 
     */
    public List<DatatypePropertyMapping> getDatatypePropertyMapping() {
        if (datatypePropertyMapping == null) {
            datatypePropertyMapping = new ArrayList<DatatypePropertyMapping>();
        }
        return this.datatypePropertyMapping;
    }

}
