//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 10:54:42 PM CET 
//


package de.biba.wrapper.newSQLWrapper.Mapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MultiJoinedTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiJoinedTable">
 *   &lt;complexContent>
 *     &lt;extension base="{}JoinedTable">
 *       &lt;sequence>
 *         &lt;element name="ThirdTable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExtendedCondition" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiJoinedTable", propOrder = {
    "thirdTable",
    "extendedCondition"
})
public class MultiJoinedTable
    extends JoinedTable
{

    @XmlElement(name = "ThirdTable")
    protected String thirdTable;
    @XmlElement(name = "ExtendedCondition")
    protected List<String> extendedCondition;

    /**
     * Gets the value of the thirdTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdTable() {
        return thirdTable;
    }

    /**
     * Sets the value of the thirdTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdTable(String value) {
        this.thirdTable = value;
    }

    /**
     * Gets the value of the extendedCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extendedCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtendedCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExtendedCondition() {
        if (extendedCondition == null) {
            extendedCondition = new ArrayList<String>();
        }
        return this.extendedCondition;
    }

}
