//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 10:54:42 PM CET 
//


package de.biba.wrapper.newSQLWrapper.Mapping;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.biba.wrapper.newSQLWrapper.Mapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.biba.wrapper.newSQLWrapper.Mapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link ClassMapping }
     * 
     */
    public ClassMapping createClassMapping() {
        return new ClassMapping();
    }

    /**
     * Create an instance of {@link ObjectPropertyMapping }
     * 
     */
    public ObjectPropertyMapping createObjectPropertyMapping() {
        return new ObjectPropertyMapping();
    }

    /**
     * Create an instance of {@link DatatypePropertyMapping }
     * 
     */
    public DatatypePropertyMapping createDatatypePropertyMapping() {
        return new DatatypePropertyMapping();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link JoinedTable }
     * 
     */
    public JoinedTable createJoinedTable() {
        return new JoinedTable();
    }

    /**
     * Create an instance of {@link ColumnMapping }
     * 
     */
    public ColumnMapping createColumnMapping() {
        return new ColumnMapping();
    }

    /**
     * Create an instance of {@link MultiJoinedTable }
     * 
     */
    public MultiJoinedTable createMultiJoinedTable() {
        return new MultiJoinedTable();
    }

}
